config/routes.rb
Rails.application.routes.draw do

  # SET HOMEPAGE
  root to: 'home#index'

  resources :salons, only: :show

  # SET ADMIN DASHBOARD
  scope "/admin" do
    resources :salons, except: :show
    get 'dashboard', to: 'dashboard#index'
  end



end

app/models/salon.rb
class Salon < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout "admin"

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @salons = Salon.all
  end
end

app/controllers/salons_controller.rb
class SalonsController < ApplicationController
  before_action :set_salon, only: [:show, :edit, :update, :destroy]
  layout :resolve_layout

  # GET /salons
  # GET /salons.json
  def index
    @salons = Salon.all
  end

  # GET /salons/1
  # GET /salons/1.json
  def show
  end

  # GET /salons/new
  def new
    @salon = Salon.new
  end

  # GET /salons/1/edit
  def edit
  end

  # POST /salons
  # POST /salons.json
  def create
    @salon = Salon.new(salon_params)

    respond_to do |format|
      if @salon.save
        format.html { redirect_to @salon, notice: 'Salon was successfully created.' }
        format.json { render :show, status: :created, location: @salon }
      else
        format.html { render :new }
        format.json { render json: @salon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salons/1
  # PATCH/PUT /salons/1.json
  def update
    respond_to do |format|
      if @salon.update(salon_params)
        format.html { redirect_to @salon, notice: 'Salon was successfully updated.' }
        format.json { render :show, status: :ok, location: @salon }
      else
        format.html { render :edit }
        format.json { render json: @salon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salons/1
  # DELETE /salons/1.json
  def destroy
    @salon.destroy
    respond_to do |format|
      format.html { redirect_to salons_url, notice: 'Salon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salon
      @salon = Salon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salon_params
      params.require(:salon).permit(:name, :description, :address)
    end

    def resolve_layout
      case action_name
      when "new", "create", "index"
        "admin"
      else
        "application"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/salons_helper.rb
module SalonsHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<% @salons.each do |s| %>

  <%= link_to s.name, s %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mojalepota2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul>
    <li><%= link_to 'Visit Website', root_path, :target => "_blank" %></li>
    <li><%= link_to 'Dashboard', dashboard_path(@dashboard) %></li>
    <li><%= link_to 'Edit Salons', salons_path(@salons) %></li>
  </ul>
  <h1>ADMIN AREA</h1>
  <hr>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mojalepota2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<ul>
  <li><%= link_to 'Dashboard', dashboard_path(@dashboard) %></li>
</ul>
<%= yield %>

</body>
</html>

app/views/salons/_form.html.erb
<%= form_for(@salon) do |f| %>
  <% if @salon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salon.errors.count, "error") %> prohibited this salon from being saved:</h2>

      <ul>
      <% @salon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salons/edit.html.erb
<h1>Editing Salon</h1>

<%= render 'form' %>

<%= link_to 'Show', @salon %> |
<%= link_to 'Back', salons_path %>

app/views/salons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Salons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salons.each do |salon| %>
      <tr>
        <td><%= salon.name %></td>
        <td><%= salon.description %></td>
        <td><%= salon.address %></td>
        <td><%= link_to 'Show', salon %></td>
        <td><%= link_to 'Edit', edit_salon_path(salon) %></td>
        <td><%= link_to 'Destroy', salon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salon', new_salon_path %>

app/views/salons/new.html.erb
<h1>New Salon</h1>

<%= render 'form' %>

<%= link_to 'Back', salons_path %>

app/views/salons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @salon.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @salon.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @salon.address %>
</p>

<%= link_to 'Edit', edit_salon_path(@salon) %> |
<%= link_to 'Back', salons_path %>